### ISSUE TITLE
Set up repository for frontend

### ISSUE THREAD

**Issue by icorbrey** [icorbrey/academy#1]
## Description

We need a repo to work in.

## Tasks

- [x] Create new repository `icorbrey/academy`
- [x] Initialize a new Astro project
- [ ] Add the Svelte integration
- [ ] Add the Tailwind CSS integration
